### ISSUE TITLE
main.py missing

### ISSUE THREAD

**Issue by denfromufa** [facebookresearch/rlstructures#4]
https://github.com/facebookresearch/rlstructures/blob/main/rlalgos/README.md

**Comment by ludc** [comment]
The README is not clear, and will be update in the next days. 

To execute an algorithm, use one of the 'run' file in the algorithm directory:
* 'a2c/run_cartpole.py' is a classical cartpole
* 'a2c/run_cartpole_pomdp.py' is a cartpole without car and pole speed as an input. It is used to test recurrent NN implementations
* 'dqn/run_q_cartpole.py' is DQN on cartpole
* etc...


The parameters of each algorithm are contained in the 'yaml' file. To execute an algorithm: `python run_file.py -cd script_directory -cn config.yaml`

For instance: `python rlstructures/rlalgos/a2c/run_cartpole.py -cd rlstructures/rlalgos/a2c -cn config.yaml`

------
 Is it more clear ?

**Comment by denfromufa** [comment]
@ludc thank you, it works with some changes, except i could run without `-cd rlstructures/rlalgos/...` argument, which makes no sense.

**Comment by ludc** [comment]
ok, thanks. I will update the documentation today.
